name: StoragePlugin
version: '${version}'
main: ru.healthanmary.storageplugin.StoragePlugin
api-version: '1.16'
authors: [healthanmary]
commands:
  getdbuser:
    description: Command
    usage: /getdbuser <name>
